# Generated by Django 3.0.3 on 2020-02-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='cls',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='image',
            field=models.FileField(null=True, upload_to='Image/'),
        ),
    ]
