# Generated by Django 3.0.3 on 2020-03-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0002_flip_image_flips_images_inventory_order_image_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
