# Generated by Django 3.0.3 on 2020-03-06 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DevApp', '0005_auto_20200302_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
